export const actionTypes = {
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    TOGGLE_BRAND : "TOGGLE_BRAND",
    TOGGLE_STOCK : "TOGGLE_STOCK",
    ADD_PRODUCT: "ADD_PRODUCT",
    LOAD_PRODUCT: "LOAD_PRODUCT"
}
